// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hleaizplcmqddbpxbdee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsZWFpenBsY21xZGRicHhiZGVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTg3NDksImV4cCI6MjA2MDk3NDc0OX0.S5QJt9RLMo7fFfW6XP2ZFQUDE22_dgaMLo3yDUVpfPY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);